name: Build & Push to GHCR

# This workflow will always push the latest tag. It will optionally push a versioned tag as well if provided with workflow_dispatch

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: "Optional image version tag (e.g., 0.10.0)"
        required: false
        default: ""

permissions:
  contents: read
  packages: write   # required to push to GHCR

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}  # owner/repo

jobs:
  docker_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lowercase IMAGE_NAME
        run: echo "LOWERCASE_IMAGE_NAME=${IMAGE_NAME,,}" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: tags
        shell: bash
        run: |
          set -euo pipefail
          BASE="${REGISTRY}/${LOWERCASE_IMAGE_NAME}"
          TAGS="${BASE}:latest"

          # Add version tag when manually dispatched and a non-empty version is provided
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VER="${{ github.event.inputs.version }}"
            if [[ -n "${VER}" ]]; then
              # Strip leading 'v' if present and lowercase
              VER="${VER#v}"
              VER="${VER,,}"
              TAGS="${TAGS},${BASE}:${VER}"
            fi
          fi

          echo "TAGS=${TAGS}" >> "$GITHUB_ENV"
          echo "Resolved tags: ${TAGS}"

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.TAGS }}
